base_config: configs/scannet/scannet.yaml

exp_name: scannet/scene0207

data_specs:
  data_path: '/media/jcx/SSD_2T/NeRF_Dataset/scannet_data/scene0207_00'
  depth_scale: 1000.0
  crop: 6
  scale_factor: 0
  use_gt: True
  max_depth: 5

decoder_specs:
  bound: [ [ 10.3,19.9 ],[ 9.0,18.0 ],[ 9.0,13.8 ] ] # nice-slam's bound + [10,10,10]